"""
VideoConf Server v2
===================
New features:
  - File sharing  (upload via HTTP POST, broadcast download link via WS)
  - Screen share  (signaled via WS so all clients know who is sharing)
  - Video playback (host broadcasts a video URL / file, clients sync play/pause)
  - Meeting summary (auto-generated by Claude when host ends meeting)
"""

import asyncio
import json
import logging
import os
import shutil
import uuid
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

import anthropic
import uvicorn
from fastapi import FastAPI, File, Form, UploadFile, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

app = FastAPI(title="VideoConf")

UPLOAD_DIR = Path("uploads")
UPLOAD_DIR.mkdir(exist_ok=True)

app.mount("/static", StaticFiles(directory="static"), name="static")
app.mount("/uploads", StaticFiles(directory="uploads"), name="uploads")


# ─── Data models ──────────────────────────────────────────────────────────────

class Participant:
    def __init__(self, pid: str, name: str, ws: WebSocket, is_host: bool = False):
        self.pid = pid
        self.name = name
        self.ws = ws
        self.is_host = is_host
        self.mic_on = True
        self.cam_on = True
        self.screen_sharing = False
        self.joined_at = datetime.now()

    def to_dict(self):
        return {
            "pid": self.pid,
            "name": self.name,
            "is_host": self.is_host,
            "mic_on": self.mic_on,
            "cam_on": self.cam_on,
            "screen_sharing": self.screen_sharing,
        }


class Room:
    def __init__(self, room_id: str, host_pid: str):
        self.room_id = room_id
        self.host_pid = host_pid
        self.participants: Dict[str, Participant] = {}
        self.locked = False
        self.created_at = datetime.now()
        self.chat_log: list = []
        self.event_log: list = []
        self.shared_files: list = []        # {name, url, size, uploader, time}
        self.current_video: Optional[dict] = None  # {url, name, playing, position}

    def add_event(self, text: str):
        ts = datetime.now().strftime("%H:%M:%S")
        self.event_log.append(f"[{ts}] {text}")
        log.info("[Room %s] %s", self.room_id, text)

    def participant_list(self):
        return [p.to_dict() for p in self.participants.values()]

    def duration_str(self):
        secs = int((datetime.now() - self.created_at).total_seconds())
        m, s = divmod(secs, 60)
        h, m = divmod(m, 60)
        return f"{h:02d}:{m:02d}:{s:02d}" if h else f"{m:02d}:{s:02d}"


rooms: Dict[str, Room] = {}


# ─── Helpers ──────────────────────────────────────────────────────────────────

async def broadcast(room: Room, msg: dict, exclude_pid: Optional[str] = None):
    dead = []
    for pid, p in room.participants.items():
        if pid == exclude_pid:
            continue
        try:
            await p.ws.send_json(msg)
        except Exception:
            dead.append(pid)
    for pid in dead:
        room.participants.pop(pid, None)


async def send(ws: WebSocket, msg: dict):
    try:
        await ws.send_json(msg)
    except Exception:
        pass


async def kick_participant(room: Room, target_pid: str):
    p = room.participants.get(target_pid)
    if not p:
        return
    await send(p.ws, {"type": "kicked"})
    room.add_event(f"{p.name} was removed from the room")
    del room.participants[target_pid]
    await broadcast(room, {
        "type": "participant_left",
        "pid": target_pid,
        "participants": room.participant_list(),
    })


# ─── AI Meeting Summary ───────────────────────────────────────────────────────

async def generate_summary(room: Room) -> str:
    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    host = next((p for p in room.participants.values() if p.is_host), None)
    host_name = host.name if host else "Unknown"
    names = [p.name for p in room.participants.values()]
    duration = room.duration_str()

    chat_text = "\n".join(
        f"  [{e['time']}] {e['name']}: {e['text']}" for e in room.chat_log
    ) or "  (无聊天记录)"

    events_text = "\n".join(f"  {e}" for e in room.event_log) or "  (无事件)"

    files_text = "\n".join(
        f"  {f['uploader']} 分享了文件: {f['name']}" for f in room.shared_files
    ) or "  (无文件分享)"

    video_text = f"  播放了视频: {room.current_video['name']}" if room.current_video else "  (无视频播放)"

    fallback = {
        "title": f"会议室 {room.room_id} 会议纪要",
        "overview": f"本次会议于 {room.created_at.strftime('%Y-%m-%d %H:%M')} 召开，由 {host_name} 主持，历时 {duration}，共 {len(names)} 人参与。",
        "attendees": names,
        "keyPoints": ["会议顺利完成", "参与者积极参与讨论"],
        "chatHighlights": [e["text"] for e in room.chat_log[:5]] if room.chat_log else ["无"],
        "sharedFiles": [f["name"] for f in room.shared_files] if room.shared_files else ["无"],
        "hostActions": [e for e in room.event_log if any(k in e for k in ["muted","removed","locked","kicked"])],
        "decisions": ["待后续跟进"],
        "nextSteps": ["请各参与者按照讨论结果执行相关任务"],
        "conclusion": f"感谢 {', '.join(names)} 的参与。"
    }

    if not api_key:
        return json.dumps(fallback)

    prompt = f"""你是专业的会议助理，请根据以下会议数据生成详细的中文会议纪要。

会议室: {room.room_id}
主持人: {host_name}
参与者: {', '.join(names)}
时长: {duration}
日期: {room.created_at.strftime('%Y-%m-%d %H:%M')}

聊天记录:
{chat_text}

会议事件:
{events_text}

文件分享:
{files_text}

视频播放:
{video_text}

请输出如下JSON格式（只输出JSON，不要加任何markdown符号）:
{{
  "title": "会议标题",
  "overview": "2-3句概述",
  "attendees": ["参与者列表"],
  "keyPoints": ["主要讨论点"],
  "chatHighlights": ["重要聊天内容"],
  "sharedFiles": ["分享的文件名"],
  "hostActions": ["主持人操作记录"],
  "decisions": ["决定事项"],
  "nextSteps": ["后续行动"],
  "conclusion": "一句话总结"
}}"""

    client = anthropic.Anthropic(api_key=api_key)
    try:
        msg = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = msg.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        return raw.strip()
    except Exception as e:
        log.error("AI summary error: %s", e)
        fallback["error"] = str(e)
        return json.dumps(fallback)


# ─── HTTP: File upload ─────────────────────────────────────────────────────────

@app.post("/upload/{room_id}")
async def upload_file(room_id: str, file: UploadFile = File(...), uploader: str = Form(...)):
    room = rooms.get(room_id)
    if not room:
        return JSONResponse({"error": "Room not found"}, status_code=404)

    # Sanitize filename
    safe_name = "".join(c for c in file.filename if c.isalnum() or c in "._- ").strip()
    unique_name = f"{uuid.uuid4().hex[:8]}_{safe_name}"
    dest = UPLOAD_DIR / unique_name

    with dest.open("wb") as f:
        shutil.copyfileobj(file.file, f)

    size = dest.stat().st_size
    url = f"/uploads/{unique_name}"
    entry = {
        "name": safe_name,
        "url": url,
        "size": size,
        "uploader": uploader,
        "time": datetime.now().strftime("%H:%M"),
    }
    room.shared_files.append(entry)
    room.add_event(f"{uploader} shared file: {safe_name} ({size//1024}KB)")

    # Broadcast to all in room
    await broadcast(room, {"type": "file_shared", "file": entry})
    return JSONResponse({"ok": True, "file": entry})


@app.get("/uploads/{filename}")
async def serve_upload(filename: str):
    path = UPLOAD_DIR / filename
    if not path.exists():
        return JSONResponse({"error": "Not found"}, status_code=404)
    return FileResponse(path, filename=filename.split("_", 1)[-1] if "_" in filename else filename)


# ─── WebSocket signaling ───────────────────────────────────────────────────────

@app.websocket("/ws/{room_id}")
async def ws_endpoint(websocket: WebSocket, room_id: str):
    await websocket.accept()
    pid = str(uuid.uuid4())[:8]
    room: Optional[Room] = None
    participant: Optional[Participant] = None

    try:
        raw = await websocket.receive_json()
        assert raw["type"] == "join"
        name = raw.get("name", "Anonymous")[:30]
        want_host = raw.get("host", False)

        if room_id not in rooms:
            room = Room(room_id, pid)
            rooms[room_id] = room
            is_host = True
        else:
            room = rooms[room_id]
            if room.locked:
                await send(websocket, {"type": "error", "message": "房间已被锁定，无法加入"})
                await websocket.close()
                return
            is_host = want_host and (len(room.participants) == 0)

        participant = Participant(pid, name, websocket, is_host)
        room.participants[pid] = participant
        room.add_event(f"{name} joined{'(host)' if is_host else ''}")

        await send(websocket, {
            "type": "joined",
            "pid": pid,
            "room_id": room_id,
            "is_host": is_host,
            "participants": room.participant_list(),
            "chat_log": room.chat_log[-50:],
            "locked": room.locked,
            "shared_files": room.shared_files,
            "current_video": room.current_video,
        })

        await broadcast(room, {
            "type": "participant_joined",
            "participant": participant.to_dict(),
            "participants": room.participant_list(),
        }, exclude_pid=pid)

        # ── Main loop ─────────────────────────────────────────────────────────
        async for raw_msg in websocket.iter_json():
            t = raw_msg.get("type", "")

            # WebRTC signaling
            if t in ("offer", "answer", "ice"):
                target = room.participants.get(raw_msg.get("target"))
                if target:
                    await send(target.ws, {"type": t, "from": pid, "fromName": name, **raw_msg})

            # Chat
            elif t == "chat":
                text = str(raw_msg.get("text", ""))[:500]
                entry = {"time": datetime.now().strftime("%H:%M"), "name": name, "pid": pid, "text": text}
                room.chat_log.append(entry)
                room.add_event(f"Chat – {name}: {text[:80]}")
                await broadcast(room, {"type": "chat", "entry": entry})

            # Screen share state
            elif t == "screen_share_state":
                participant.screen_sharing = raw_msg.get("sharing", False)
                room.add_event(f"{name} {'started' if participant.screen_sharing else 'stopped'} screen sharing")
                await broadcast(room, {
                    "type": "screen_share_state",
                    "pid": pid,
                    "name": name,
                    "sharing": participant.screen_sharing,
                    "participants": room.participant_list(),
                })

            # Video playback (host only broadcasts, all clients sync)
            elif t == "video_load":
                if not participant.is_host:
                    continue
                room.current_video = {
                    "url": raw_msg.get("url", ""),
                    "name": raw_msg.get("name", "视频"),
                    "playing": False,
                    "position": 0,
                }
                room.add_event(f"Host loaded video: {room.current_video['name']}")
                await broadcast(room, {"type": "video_load", "video": room.current_video})

            elif t == "video_control":
                if not participant.is_host:
                    continue
                action = raw_msg.get("action")  # play | pause | seek
                position = raw_msg.get("position", 0)
                if room.current_video:
                    room.current_video["playing"] = (action == "play")
                    room.current_video["position"] = position
                await broadcast(room, {
                    "type": "video_control",
                    "action": action,
                    "position": position,
                }, exclude_pid=pid)

            elif t == "video_close":
                if not participant.is_host:
                    continue
                room.current_video = None
                room.add_event("Host closed video playback")
                await broadcast(room, {"type": "video_close"})

            # Host controls
            elif t == "host_mute_mic":
                if not participant.is_host: continue
                target = room.participants.get(raw_msg["target"])
                if target:
                    muted = raw_msg.get("muted", True)
                    target.mic_on = not muted
                    room.add_event(f"Host {'muted' if muted else 'unmuted'} {target.name}'s mic")
                    await send(target.ws, {"type": "force_mute_mic", "muted": muted})
                    await broadcast(room, {"type": "participant_updated", "participants": room.participant_list()})

            elif t == "host_mute_cam":
                if not participant.is_host: continue
                target = room.participants.get(raw_msg["target"])
                if target:
                    muted = raw_msg.get("muted", True)
                    target.cam_on = not muted
                    room.add_event(f"Host {'disabled' if muted else 'enabled'} {target.name}'s cam")
                    await send(target.ws, {"type": "force_mute_cam", "muted": muted})
                    await broadcast(room, {"type": "participant_updated", "participants": room.participant_list()})

            elif t == "host_kick":
                if not participant.is_host: continue
                if raw_msg.get("target") != pid:
                    await kick_participant(room, raw_msg["target"])

            elif t == "host_lock":
                if not participant.is_host: continue
                room.locked = raw_msg.get("locked", True)
                room.add_event(f"Host {'locked' if room.locked else 'unlocked'} the room")
                await broadcast(room, {"type": "room_locked", "locked": room.locked})

            elif t == "end_meeting":
                if not participant.is_host: continue
                room.add_event("Meeting ended by host")
                await broadcast(room, {"type": "meeting_ended"}, exclude_pid=pid)
                summary_json = await generate_summary(room)
                await send(websocket, {
                    "type": "meeting_summary",
                    "summary": summary_json,
                    "duration": room.duration_str(),
                })

            elif t == "media_state":
                participant.mic_on = raw_msg.get("mic_on", participant.mic_on)
                participant.cam_on = raw_msg.get("cam_on", participant.cam_on)
                await broadcast(room, {"type": "participant_updated", "participants": room.participant_list()})

            elif t == "ping":
                await send(websocket, {"type": "pong"})

    except WebSocketDisconnect:
        pass
    except Exception as e:
        log.exception("WS error: %s", e)
    finally:
        if room and participant:
            room.participants.pop(pid, None)
            room.add_event(f"{participant.name} left")
            await broadcast(room, {
                "type": "participant_left",
                "pid": pid,
                "participants": room.participant_list(),
            })
            if not room.participants:
                rooms.pop(room_id, None)


# ─── HTTP pages ────────────────────────────────────────────────────────────────

@app.get("/")
async def index():
    with open("static/index.html", "r", encoding="utf-8") as f:
        return HTMLResponse(f.read())

@app.get("/room/{room_id}")
async def room_page(room_id: str):
    with open("static/index.html", "r", encoding="utf-8") as f:
        return HTMLResponse(f.read())

if __name__ == "__main__":
    print("\n" + "="*55)
    print("  🎥 VideoConf Server v2")
    print("="*55)
    print("  Local:   http://localhost:8000")
    print("  Set ANTHROPIC_API_KEY for AI meeting summary")
    print("="*55 + "\n")
    uvicorn.run("server:app", host="0.0.0.0", port=8000, reload=False)
